### ISSUE TITLE
Doesn't seem to work for markdown files

### ISSUE THREAD

**Issue by postsolar** [neurocyte/zat#5]
```console
$ ./zig-out/bin/zat -l markdown README.md
```

outputs unformatted text.

**Comment by neurocyte** [comment]
It does include the tree-sitter markdown parser. Unfortunately most vscode themes provide very little (or no) highlighting of markdown. Try `zat --theme OneDark-Pro README.md` to see that it is actually working.

Also note, there is no tree-sitter injection support just yet, so markdown's inline code blocks will not be hightlighted with embedded language parser.
