### ISSUE TITLE
Feature request: highlight range

### ISSUE THREAD

**Issue by NTBBloodbath** [neurocyte/zat#6]
Hey,

I'm loving `zat` so far, being powered by `tree-sitter` is a killer feature for me, I've even replaced `bat` with it already!

I recently saw that the feature of highlighting a line in the file was added, which is great, especially when looking to share something specific in the file with someone! However, sometimes I would like to be able to highlight a range of lines (e.g. when wanting to highlight a function in a `bash` file) :)

Thanks for the work here, I love being able to replace my system tools with alternatives made in Zig 😄

**Comment by neurocyte** [comment]
@NTBBloodbath Any suggestions on the format of the cli option for this? I'm think something like this:

- `--highlight 10` highlight just a single whole line
- `--highlight 10,12` highlight a line range
- `--highlight 10:5,:15` hightlight a byte range on line 10 (or perhaps `10:5:15` and skip the comma)
- `--highlight 10:5,12:15` highlight a byte range across multiple lines

Thoughts?

**Comment by NTBBloodbath** [comment]
That syntax looks natural, I like it :p

**Comment by neurocyte** [comment]
On second thoughs, I will not implement column highlighting. That would require adding a large dependency for proper unicode support. That is out of scope at the moment.

I will still add multi line highlighting though.
